name: ClawMobile
options:
  bundleIdPrefix: com.clawstaffer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift
    from: "0.21.0"

targets:
  ClawMobile:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ClawMobile
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.clawstaffer.mobile
        INFOPLIST_FILE: ClawMobile/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: ""
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXNN
      - package: mlx-swift
        product: MLXRandom
      - package: mlx-swift
        product: MLXFast
